version: '3.8'

services:
  data-collector:
    build: 
      .
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data # Volume for persisting the database
    env_file:
      - .env

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard  # Separate Dockerfile for the dashboard (see below)
    ports:
      - "8080:8080"  # Expose port 8080
    volumes:
      - ./data:/app/data # Share the database volume
    depends_on:
      - data-collector
    env_file:
      - .env
