version: '3.8'

services:
  data-collector:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # This mounts the local ./data directory to /app/data in the container
    
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard  
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data  # Make sure both containers share the same volume
    depends_on:
      - data-collector
    env_file:
      - .env

volumes:
  data:  # Named volume definition 
